### ISSUE TITLE
why I get this : Failed to resolve: io.getstream:stream-video-android-compose:0.5.1

### ISSUE THREAD

**Issue by razaghimahdi** [GetStream/stream-video-android#1015]
why I get this : Failed to resolve: io.getstream:stream-video-android-compose:0.5.1
I even get this from 0.5.0 and 0.4.3
How to fix that?

**Comment by skydoves** [comment]
Hey @razaghimahdi, the package name has been changed to `io.getstream:stream-video-android-ui-compose` since version 0.5.0.
