### ISSUE TITLE
Can not build demo app

### ISSUE THREAD

**Issue by linhnv106** [GetStream/stream-video-android#1037]
Hi Team,
I got issue when trying to run demo-app.
`Task 'prepareKotlinBuildScriptModel' not found in project ':demo-app'.
`
Any idea @skydoves ?
Thanks.

**Comment by skydoves** [comment]
Hey @linhnv106, would you add the task below to the app's `gradle.build` file?

```groovy
tasks.register("prepareKotlinBuildScriptModel"){}
```

**Comment by skydoves** [comment]
Hey @linhnv106, we're going to close this issue for now. If you still face the same issue, please let us know!
