### ISSUE TITLE
The sound from the microphone is interrupted on the locked screen on Samsung phones with Android 14

### ISSUE THREAD

**Issue by sgolovanov43** [GetStream/stream-video-android#1118]
**Describe the bug**
The sound from the microphone is interrupted on the locked screen on Samsung phones with Android 14. 
In an application that uses the webrtc module, the microphone sound continues to be received and the conversation is being recorded

**SDK version**
- 1.1.1

**To Reproduce**
Lock screen in active call (microphone mute) unlock screen (microphone work)

**Expected behavior**

**Device:**
 - Samsung S22, Samsung S23
 - Android version: 14

**Screenshots**

**Comment by aleksandar-apostolov** [comment]
Hey @sgolovanov43 thanks for the report.
Which version of the SDK are you using exactly?

**Comment by sgolovanov43** [comment]
Good day, Aleksandar.
We use the SDK of version 1.1.1. But I tried 1.1.3 and that version is still not working.

Best regards,
Sergey Golovanov

**Comment by aleksandar-apostolov** [comment]
@sgolovanov43 
can you share your `dependencies` block. Our latest release is `1.0.6`.
