### ISSUE TITLE
Ringing tutorial demo app: Changing orientation resets call each time

### ISSUE THREAD

**Issue by Miara** [GetStream/stream-video-android#1159]
**Describe the bug**
When I change orientation during call, then it is reseted, and current user is calling the other again. You can recreate it each time. 

**SDK version**
- 10.0.12

**To Reproduce**
1. Log in to user1 on 1 device, and on user2 on second device.
2. Call user2
3. Answer call by user 2
4. Change phone orientation - rotate device
5. On device 2: user1 is disconnected from call. on device 1: user1 is calling user2 again.

**Expected behavior**
Call should be continued

**Device:**
 - Vendor and model: Samsung Galaxy Note 10+
 - Android version: 12

**Comment by aleksandar-apostolov** [comment]
Hey @Miara 

Thanks for the report.
We will look into it.

Regards,
Alex

**Comment by aleksandar-apostolov** [comment]
Hey @Miara
This is a UI issue with the `StreamCallActivity` we are going to release a fix for this next week.

Regards,
Alex
