### ISSUE TITLE
Missing buttons in horizontal orientation

### ISSUE THREAD

**Issue by Miara** [GetStream/stream-video-android#1161]
**Describe the bug**
When I am on landscape orientation, there are no buttons available. Nor `end call` button, nor `mute microphone button` neither any other. I know that it could be made in a client app, but I think If you provide full UI components for portrait mode, it should be set for landscape as well. 

Custom adding buttons makes some problems with `picture in picture` mode that shouldn't actually have buttons, as there is small space for floating video.

**SDK version**
- 10.0.12

**Expected behavior**
Actions button should be visible on landscape mode.

**Device:** Appears on each device

**Screenshots**
![image](https://github.com/user-attachments/assets/f68dea53-8db7-496b-bec4-88c32a144cd4)
![image](https://github.com/user-attachments/assets/9e61be25-ac74-4f83-9761-119d808d31f1)

**Comment by aleksandar-apostolov** [comment]
Hey @Miara 
The controls are available via the more menu on the top right. This is how it is in demo-app.
The UI can be customised further using the SDK.

![image](https://github.com/user-attachments/assets/8279bf98-0d42-43ec-8bb3-14c3894d3f65)

**Comment by Miara** [comment]
Thanks @aleksandar-apostolov ! I haven't noticed it before
