### ISSUE TITLE
Wrong video rotation in landscape mode

### ISSUE THREAD

**Issue by Miara** [GetStream/stream-video-android#1162]
**Describe the bug**
There are few bugs with video rotation when being in landscape mode:
- In Picture in picture, when camera is front, video is displayed upside down (probably the reason is that front camera has reverse orientation then back camera (Screenshot 1)
- When opening picture in picture in landscape mode - video is cut and it is displayed like it was still vertical orientation (look at Screenshot 2)

**SDK version**
- demo-app on develop (latest release was 10.0.12)

**Expected behavior**
- in case 1: Video is not upside-down
- In case 2: Video is horizontal - not vertical

**Device:**
 - Vendor and model: Samsung
 - Android version: 12

**Screenshots**
![image](https://github.com/user-attachments/assets/99649541-f38b-4e71-b6d4-6c7bffd8285c)
![image](https://github.com/user-attachments/assets/ee64f821-ea13-47a9-91c3-d9037ba0022c)

**Comment by aleksandar-apostolov** [comment]
Hi @Miara 

Thanks for your report. The PiP needs to be revisited. The camera frame comes from the WebRTC library, we will look there for the fix. 

Keeping this open and I will update the issue when we've checked the WebRTC.

Regards,
Alex
