### ISSUE TITLE
Picture in picture: I don't see other call participant, but only me

### ISSUE THREAD

**Issue by Miara** [GetStream/stream-video-android#1163]
**Describe the bug**
When I am in Picture in Picture mode, and I talk with someone, I don't see person that is currently speaking, but I only see myself. In all other call application I can see person that is currently talking. I am not sure if it is bug or feature, but I will give a try with reporting a bug. And if this is not bug, then could such feature be added to be able to observe other person in `PiP` mode?

**SDK version**
- 10.0.12 in demo-app

**To Reproduce**
1. Start call with someone
2. Go to `Picture in picture` mode
3. Disable microphone
4. Talk from other user's device
5. You can see yourself all the time

**Expected behavior**
I want to see person that is speaking, or at least to have possibility of configuration

**Device:** Each device

**Comment by aleksandar-apostolov** [comment]
Hey @Miara 
The person who is displayed in PiP is the so called `dominantSpeaker` there are several rules that decide which participant it is. If there is no `dominantSpeaker`,  you see yourself.

We will revisit this to be sure.

Regards,
Alex
