### ISSUE TITLE
Call Settings for custom call type are not applied to a call

### ISSUE THREAD

**Issue by Miara** [GetStream/stream-video-android#1173]
**Describe the bug**
I created custom call types: `video` and `audio` in GetStream Dasboard. I set settings for each of these types. For example for video I set these settings:

![image](https://github.com/user-attachments/assets/73cf3989-80b3-4e3b-9823-573a70680b2f)

And in custom settings:

![image](https://github.com/user-attachments/assets/e03a62f2-cb00-434d-a58b-ec44e80ce1a7)

Hovewer after call is started - microphone is disabled and speaker is disabled as well - I can hear only voice from Earpiece audio source. 

I'm not sure it something is not ok with console web implementation, or backend implementation, or Android SDK implementation, or even I did something wrong - but i guess it's bug on your side, because I create as simple call activity as possible, using only your code:

    {
    @OptIn(StreamCallActivityDelicateApi::class)
    class CallActivity : ComposeStreamCallActivity() {
    
        override val uiDelegate: StreamActivityUiDelegate<StreamCallActivity> = StreamCallActivityComposeDelegate()
        override val configuration: StreamCallActivityConfiguration =
            StreamCallActivityConfiguration(closeScreenOnCallEnded = false)
    }
    }

**SDK version**
- 10.0.13

**To Reproduce**
1. Create new call type, and set such settings as mentioned above in GetStream Dashboard
2. Start call with new type
3. Microphone is disabled, earpiece is selected instead of speakerphone

**Expected behavior**
Microphone is enabled, speaker mode is enabled

**Device:**
 - Vendor and model: Samsung Galaxy Note 10+
 - Android version: 12

**Comment by Miara** [comment]
I see that the problem is only with audio settings. Video settings seem to work corretly. 

Here is the hack I did to make it working as expected:

    @OptIn(StreamCallActivityDelicateApi::class)  
	class CallActivity : ComposeStreamCallActivity() {  
  
    override val uiDelegate: StreamActivityUiDelegate<StreamCallActivity> = CallActivityUIDelegate()  
    override val configuration: StreamCallActivityConfiguration =  
        StreamCallActivityConfiguration(closeScreenOnCallEnded = false)  
  
    override fun create(  
        call: Call,  
	  ring: Boolean,  
	  members: List<String>,  
	  onSuccess: (suspend (Call) -> Unit)?,  
	  onError: (suspend (Exception) -> Unit)?  
	    ) {  
	        val isVideo = call.type == "video"  
	  lifecycleScope.launch(Dispatchers.IO) {  
	  val instance = StreamVideo.instance()  
	            val result = call.create(  
	                // List of all users, containing the caller also  
	  memberIds = members + instance.userId,  
	  // If other users will get push notification.  
	  ring = ring,  
	  settings = CallSettingsRequest(  
	                    audio = AudioSettingsRequest(  
	                        defaultDevice = if(isVideo) AudioSettingsRequest.DefaultDevice.Speaker else AudioSettingsRequest.DefaultDevice.Earpiece,  
	  micDefaultOn = true  
	  ),  
	  )  
	            )  
	            result.onOutcome(call, onSuccess, onError)  
	        }  
	  }  
	  
	    private suspend fun <A : Any> Result<A>.onOutcome(  
	        call: Call,  
	  onSuccess: (suspend (Call) -> Unit)? = null,  
	  onError: (suspend (Exception) -> Unit)? = null,  
	  ) = withContext(Dispatchers.Main) {  
	  onSuccess?.let {  
	  onSuccessSuspend {  
	  onSuccess(call)  
	            }  
	 }  onError?.let {  
	  onErrorSuspend {  
	  onError(Exception(it.message))  
	            }  
	 } }}

**Comment by liviu-timar** [comment]
Hi @Miara, we'll look into it as soon as possible, thanks for reporting this issue.

**Comment by Miara** [comment]
I see that even my hack partially works, because when I have this custom setting:

<img width="684" alt="image" src="https://github.com/user-attachments/assets/07c0b34c-f7a0-4bee-a123-22e436842a2d">

`micDefaultOn` works, so after call is started, microphone is enabled

but `speakerDefaultOn` doesn't work. even if this is set to true, speaker is disabled

**Comment by liviu-timar** [comment]
Hi Miara,

We have PR #1191 that solves part of the Dashboard settings propagation issues. Now `Speaker on By Default` and `Default Device` are reflected in the call. These changes will be available in a new version next week.

We'll handle the camera & mic `on/off` settings in another PR.

Thank you!

**Comment by Miara** [comment]
Hi @aleksandar-apostolov any update regarding camera & mic `on/off` settings? It is still not working in latest version
