### ISSUE TITLE
Could you add possibility to check whether other user have any active device at the moment?

### ISSUE THREAD

**Issue by Miara** [GetStream/stream-video-android#1195]
### Context & proposal

Hi guys! 

I want to integrate your SDK, and my business case is that currently I have my own audio/video streaming calls implementation, but I want to use your SDK and I want to control it with feature flag to have both calls (my own old calls, and new calls with your SDK)

I want to make smooth transition to new calls with your SDK, so it could be a situation, that some user using the app that I call to, doesn't have GetStream calls, but only old calls.

How can I check using GetStream SDK if other user has any registered device at the moment - using his ID? How could I achieve it? is it available in your SDK, or it is matter of a new feature?

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Add method in Stream SDK that allows to ask backend about user presence - whether he has any active device registered - or not. 

-----

PS. I tried to ask you about this here: https://github.com/GetStream/stream-video-android/discussions , but It looks like nobody is looking there - that's why I decided to create new ticket.

**Comment by Miara** [comment]
Also, when I call somebody that is not registered in GetStream, I such error message:

```
{"code":4,"message":"GetOrCreateCall failed with error: \"The following users are involved in call create operation, but don't exist: [61b339db7ee7450007267e27]. Please create users before referencing them in a call. It is recommended to create users server-side.\"","StatusCode":400,"duration":"0.00ms","more_info":"https://getstream.io/chat/docs/api_errors_response","details":[]}
```

But when I look into suggested documentation: https://getstream.io/chat/docs/api_errors_response --> code 4, and status code 400 - are hard to determine whether the reason is not registered user. These codes are to generic

Would it be possible to provide separate code for such case, to not analyze `string` error mesage?

**Comment by aleksandar-apostolov** [comment]
Hi @Miara 

I need to check this with the backend and product teams if we want to do it. Usually this kind of stuff would be the responsibility of the integration app. 

Btw, we have a notification for the issues but not for the discussions which we check every other week :) 

Regards,
Alex

**Comment by Miara** [comment]
Thanks Alex! 

It is no problem for me to have responsibility of checking if other user has any device registered actively... But how can I do it? 😄 

The only way I see is to... compare `error_message` string from backend response, but I am affraid what happens if backend will change a message. 

Code would be much better - as something solid and constant with specific meaning

**Comment by aleksandar-apostolov** [comment]
Hi @Miara 

The correct way to proceed with this is to open a support ticket, so our support team will propagate it correctly to all involved parties.

When you do so, please reference this GitHub issue in your ticket.

Regards,
Alex
