### ISSUE TITLE
Implement overflow actions + popup list following the design guidelines 

### ISSUE THREAD

**Issue by skydoves** [GetStream/stream-video-android#483]
Implement overflow actions + popup list following the design guidelines.

**Comment by shashankdaima** [comment]
hey @skydoves, i want to contribute to this feature. Can you show the direction of your design guidelines and slack/discord of stream?
Thanks.

**Comment by skydoves** [comment]
Hey @shashankdaima. this feature was actually already implemented. Thanks for having an interest in this repository. I will let you know if there's another thing that you can contribute to this repo :)

**Comment by shashankdaima** [comment]
Thanks @skydoves , but do you have some discord community or anything like that?
