### ISSUE TITLE
This library increases the size of signed apk from 8 to 48 mb

### ISSUE THREAD

**Issue by razaghimahdi** [GetStream/stream-video-android#791]
So I noticed after getting signed apk, app has too many sizes (48mb) then I figured out without this library apk would be only 8 mb !!!
is there any solution ?

**Comment by DanielNovak** [comment]
You can also drag&drop APK or AAB files into Android Studio - it will show you an overview of the components inside and their size. 

In case of our demo the full APK size is 60MB, AAB size is 37MB but actual full download size on a reference device from Google Play is 23.7MB. Incremental update is even smaller.

**Comment by DanielNovak** [comment]
We have just measured the size of our demo application with `isMinifyEnabled = true` and it's around 10.6MB with both Video and Chat SDKs. This is the size indicated by Google Play for a specific device (the total size is larger, but it's never delivered to the end client in full size from Google Play).

**Comment by skydoves** [comment]
We're closing this issue since @DanielNovak already commented on this.
