### ISSUE TITLE
calling LaunchCallPermissions for first time, makes micro off

### ISSUE THREAD

**Issue by razaghimahdi** [GetStream/stream-video-android#853]
calling LaunchCallPermissions for first time, makes micro off. user have to close the call and restart it, otherwise micro doesn't work. 
ver: 0.3.4

**Comment by amitYadavDev** [comment]
Hey @skydoves @DanielNovak, can I work on this issue.

**Comment by DanielNovak** [comment]
@amitYadavDev Sure - thanks for offering your help :-). The only thing we need would be to sign the CLA (the link is in the pull request draft if you open it) https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform

**Comment by amitYadavDev** [comment]
@DanielNovak done.

**Comment by skydoves** [comment]
@razaghimahdi This API has undergone mcuh refactoring since version 0.3.4 (currently at 0.5.7), and the issue appears to be resolved. If you continue to encounter the same problem, please reopen the issue and mention the assignees! (@aleksandar-apostolov and me)
