### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property audioHandler has not been initialized

### ISSUE THREAD

**Issue by razaghimahdi** [GetStream/stream-video-android#865]
on latest version, when I try to leave call, sometimes says: "kotlin.UninitializedPropertyAccessException: lateinit property audioHandler has not been initialized" and it causes crash. why? how to handle that? but it shouldn't crash, right?

**Comment by DanielNovak** [comment]
This shouldn't crash but a stack trace would be helpful. This is throw from the `MicrophoneManager` [here](https://github.com/GetStream/stream-video-android/blob/4a70c4c0306593f9b7645b5f4fc6335e25924fe1/stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/MediaManager.kt#L317). This can be accessed from outside with `call. If the internal `setup()` was not called yet then it would crash. This means that something is manipulating the microphone manager before it was properly set up. 
It could be that the call wasn't set up properly or was missing the audio completely for some reason. 

We can add some initialisation checks there but it would be good if we had a stacktrace.

**Comment by DanielNovak** [comment]
It could be that `cleanup()` in a call where the microphone wasn't enabled or disabled yet (in our Compose code we always call this function). We will prepare a fix later today that will prevent this specific case.
