### ISSUE TITLE
[Suggestion] Allow customize the renderer of FloatingParticipantVideo in CallContent

### ISSUE THREAD

**Issue by workspace** [GetStream/stream-video-android#932]
### Context & proposal

The videoRenderer in the CallContent composable only applies to the grid in the ParticipantLayout. Sometimes the layout of a floating video also needs to be customized, so it would be nice to add an argument called floatingVideoRenderer.

Implementation would be simple: an argument named floatingVideoRenderer would be added to CallContent, ParticipantLayout, ParticipantsRegularGrid, OrientationVideoRenderer, LandscapeVideoRenderer, and PortraitVideoRenderer.

### Acceptance criteria
- [ ] add floatingVideoRenderer to related composables

**Comment by skydoves** [comment]
@workspace Thank you for your valuable suggestion! The issue has been addressed in #938, and you can expect it to be included in the upcoming stable release.
